apiVersion: v2
name: geonode-k8s
version: 1.2.3-alpha
description: "Helm Chart for Geonode. Supported versions: Geonode: 4.4.0, Geoserver: 2.24.4-v1, pyCSW: 2.6.1"
keywords:
  - geonode
  - geospatial
  - geodata
  - SDI
  - http
  - web
  - python
  - geoserver
  - postresql
  - postgis
  - rabbitmq
  - memcached
  - django
icon: https://raw.githubusercontent.com/zalf-rdm/geonode-k8s/main/docs/img/geonode-k8s-logo.png
annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/zalf-rdm/geonode-k8s/
    - name: Docs
      url: https://geonode-k8s.readthedocs.io/en/latest/
    - name: support
      url: https://github.com/zalf-rdm/geonode-k8s/issues/
    - name: Geonode
      url: https://www.geonode.org/
  artifacthub.io/category: "storage"
  artifacthub.io/license: "GPL3"
home: https://geonode.org/
sources:
  - https://github.com/zalf-rdm/geonode-k8s
  - https://github.com/geonode/geonode
maintainers:
  - name: mwallschlaeger
    email: marcel.wallschlaeger@zalf.de
    url: https://github.com/mwallschlaeger
dependencies:
  - name: postgres-operator
    version: ~1.12.0
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
    condition: postgres-operator.enabled
  - name: rabbitmq
    version: ~15.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: memcached
    repository: https://charts.bitnami.com/bitnami
    condition: geonode.memcached.enabled
    version: ~7.5.2
