global:
  storageClass: standard

geonode:
  replicaCount: 1 # not working yet

  general:
    debug: True
    debug_static: True

  persistant:
    storageSize: 2Gi

  ingress:
    enabled: False
    externalScheme: http
    externalDomain: geonode

  superUser:
    password: geonode

  mail:
    enabled: False

  ldap:
    enabled: False

  register:
    open_signup: True
    email_verification: "False"
    authentication_method: username_email

postgres-operator-ui:
  enabled: False

postgres-operator:
  enabled: True

postgres:
  operator_manifest:
    storageSize: 2Gi
    numberOfInstances: 1
    postgres_version: 15

rabbitmq:
  replicaCount: 1
  auth:
    username: rabbituser
    password: rabbit_password
