# geoserver stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "geoserver_pod_name" . }}"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      org.geonode.instance: "{{ include "geoserver_pod_name" . }}"
  serviceName: "{{ include "geoserver_pod_name" . }}"
  replicas: 1
  template:
    metadata:
      labels:
        org.geonode.instance: "{{ include "geoserver_pod_name" . }}"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/geoserver/geoserver-env.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 3
      initContainers:
      - name: data-dir-conf
        image: geonode/geoserver_data:{{ .Values.geoserver.image.tag }}
        command:
        - sh
        - -c
        - |
          # Copy defaults from data container
          cp -r /tmp/geonode/downloaded/data /geoserver_data

          # Copy overrides from ConfigMap
          cp /overrides/notifier.xml /geoserver_data/data/notifier/

          # Update custom EPSG codes
          cat /geoserver_data/data/user_projections/epsg.properties > /tmp/epsg.properties
          {{- range .Values.geoserver.customEPSGs }}
          echo '{{ . }}' >> /tmp/epsg.properties
          {{- end }}
          {{- range .Values.geoserver.extraCustomEPSGs }}
          echo '{{ . }}' >> /tmp/epsg.properties
          {{- end }}
          sort -u /tmp/epsg.properties > /geoserver_data/data/user_projections/epsg.properties
        volumeMounts:
        - name: "{{ include "persistant_volume_name" . }}"
          mountPath: /geoserver_data/data
          subPath: geoserver-data-dir
        - name: geoserver-notifier-xml
          mountPath: /overrides

      containers:
      - name: {{ .Values.geoserver.container_name }}
        image: "{{ .Values.geoserver.image.name }}:{{ .Values.geoserver.image.tag }}"
        # temporary overloading entry point to fix j2 template: https://github.com/GeoNode/geonode/issues/11318
        command:
        - sh
        - -c
        - |
          TMP_DB_PORT={{ include "database_port" . }}
          {{`sed -i 's/db:5432/{{ DATABASE_HOST }}:$TMP_DB_PORT/g' /templates/geofence/geofence-datasource-ovr.properties.j2`}}
          /usr/local/tomcat/tmp/entrypoint.sh

        ports:
        - containerPort: {{ .Values.geoserver.port }}

        envFrom:
        - configMapRef:
            name:  {{ include "geoserver_pod_name" . }}-env
        - secretRef:
            name: {{ default "geoserver-secret" .Values.geoserver.secret.existingSecretName | quote }}

        env:
          # read auto generated password from secret
          - name: GEONODE_GEODATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "database_geodata_password_secret_key_ref" . }}
                key: password

        volumeMounts:
        - name: "{{ include "persistant_volume_name" . }}"
          mountPath: /geoserver_data/data
          subPath: geoserver-data-dir

        readinessProbe:
          tcpSocket:
            port: {{ .Values.geoserver.port }}
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 15

        livenessProbe:
          tcpSocket:
            port: {{ .Values.geoserver.port }}
          initialDelaySeconds: 180
          periodSeconds: 5
          failureThreshold: 15

        resources:
          requests:
            memory: {{ .Values.geoserver.resources.requests.memory }}
            cpu: {{ .Values.geoserver.resources.requests.cpu }}
          limits:
            memory: {{ .Values.geoserver.resources.limits.memory }}
            cpu: {{ .Values.geoserver.resources.limits.cpu }}

      volumes:
      - name: geoserver-notifier-xml
        configMap:
          name: {{ .Release.Name }}-geoserver-notifier-xml
      - name: "{{ include "persistant_volume_name" . }}"
        persistentVolumeClaim:
          claimName: pvc-{{ .Release.Name }}-geonode
